base_url = "https://swamp-lang.org"
title = "Swamp Language"
theme = "swamp"
compile_sass = true
build_search_index = false


[markdown]
highlight_code = true
highlight_theme = "lily-dark"
# extra_syntaxes = ["syntax-themes"]  # Not sure if this is needed?
extra_syntaxes_and_themes = ["syntax-themes"]
smart_punctuation = true

[extra]
author = "Swamp"
description = "Official documentation for the Swamp programming language"
show_social = true
toc = true

# Navigation
navbar_items = [
  { code = "en", nav_items = [
    { url = "/", name = "Home" },
    { url = "/specification/", name = "Specification" },
    { url = "/install/", name = "Install" },
    { url = "/roadmap/", name = "Roadmap" },
		{ url = "/idioms/", name = "Idioms" },
  ]}
]


[extra.footer]
info = 'Documentation by [catnipped](https://bsky.app/profile/ossianboren.bsky.social). Swamp Language Copyright &copy; 2024 Peter Bjorklund. All rights reserved.'

[extra.social]
github = "swamp/script"
